kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-mgmt-spire-server

subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: spire-mgmt
roleRef:
  kind: ClusterRole
  name: spire-mgmt-spire-server
  apiGroup: rbac.authorization.k8s.io
