apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: "spire-agent"
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - "system:serviceaccount:spire-mgmt:spire-agent"
volumes:
  - configMap
  - hostPath
  - projected
  - secret
  - emptyDir
allowedCapabilities: null
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
requiredDropCapabilities: null
---
# Source: spire/charts/spire-server/templates/controller-manager-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: spire-mgmt-spire-controller-manager-webhook
fsGroup:
  type: RunAsAny
groups: []
priority: null
requiredDropCapabilities: null
seccompProfiles:
  - '*'
