apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: spire-spiffe-csi-driver
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:spire-mgmt:spire-spiffe-csi-driver
volumes:
  - configmap
  - hostPath
  - secret
allowedCapabilities: null
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
requiredDropCapabilities: null
