apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-mgmt-spire-oidc-discovery-provider
spec:
  className: "spire-mgmt-spire"
  hint: oidc-discovery-provider
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      component: oidc-discovery-provider
      release: spire
      release-namespace: spire-mgmt
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - spire-mgmt
      - spire-server
      - spire-system
  dnsNameTemplates:
    - oidc-discovery.{{ .TrustDomain }}
  autoPopulateDNSNames: true
