apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-client
spec:
  secretName: selfsigned-client
  literalSubject: UID=uid-test, CN=user, OU=testOU, O=test, DC=domain-test
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
