apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-spiffe-oidc-discovery-provider
  namespace: spire-mgmt
data:
  oidc-discovery-provider.conf: |
    {
      "domains": [
        "spire-spiffe-oidc-discovery-provider",
        "spire-spiffe-oidc-discovery-provider.spire-mgmt",
        "spire-spiffe-oidc-discovery-provider.spire-mgmt.svc.cluster.local",
        "oidc-discovery.apps.tgeer-test.devcluster.openshift.com"
      ],
      "health_checks": {
        "bind_port": "8008",
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "log_level": "debug",
      "serving_cert_file": {
        "addr": ":8443",
        "cert_file_path": "/certs/tls.crt",
        "key_file_path": "/certs/tls.key"
      },
      "workload_api": {
        "socket_path": "/spiffe-workload-api/spire-agent.sock",
        "trust_domain": "apps.tgeer-test.devcluster.openshift.com"
      }
    }
  spiffe-helper.conf: |
    agent_address = "/spiffe-workload-api/spire-agent.sock"
    cert_dir = "/certs"
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "ca.pem"

