apiVersion: v1
kind: ConfigMap
metadata:
  name: "spire-agent"
  namespace: "spire-mgmt"
data:
  agent.conf: |
    {
      "agent": {
        "data_dir": "/var/lib/spire",
        "log_level": "debug",
        "retry_bootstrap": true,
        "server_address": "spire-server.spire-mgmt",
        "server_port": "443",
        "socket_path": "/tmp/spire-agent/public/spire-agent.sock",
        "trust_bundle_path": "/run/spire/bundle/bundle.crt",
        "trust_domain": "apps.tgeer-test.devcluster.openshift.com"
      },
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "9982",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "KeyManager": [
          {
            "memory": {
              "plugin_data": null
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "cluster": "example-cluster"
              }
            }
          }
        ],
        "WorkloadAttestor": [
          {
            "k8s": {
              "plugin_data": {
                "disable_container_selectors": false,
                "node_name_env": "MY_NODE_NAME",
                "skip_kubelet_verification": true,
                "use_new_container_locator": true,
                "verbose_container_locator_logs": false
              }
            }
          }
        ]
      }
    }
